// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCecYmShSWE2QxOT96OmvWwV4wEXRrMpDM',
    appId: '1:279267591480:web:c8cd6734cd6cc183d92dcd',
    messagingSenderId: '279267591480',
    projectId: 'chatapp-ba8f7',
    authDomain: 'chatapp-ba8f7.firebaseapp.com',
    storageBucket: 'chatapp-ba8f7.firebasestorage.app',
    measurementId: 'G-X14Q2WMYKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSBEBZgHp-tC_TmARsxqMKYd6upFMu4rc',
    appId: '1:279267591480:android:8454e67b13b5c1ffd92dcd',
    messagingSenderId: '279267591480',
    projectId: 'chatapp-ba8f7',
    storageBucket: 'chatapp-ba8f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEQWIn65hgwNqb-xYJ408QgqR-1tdi-Qk',
    appId: '1:279267591480:ios:15e0dc7d2636363ad92dcd',
    messagingSenderId: '279267591480',
    projectId: 'chatapp-ba8f7',
    storageBucket: 'chatapp-ba8f7.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
